const DEFAULT_PAGE_SIZE = 10;
const DEFAULT_PAGE_NUMBER = 1;
const GET_PRODUCTS_FIELDS = 'id name price images';
const CACHE_DURATION = 300;
const MAX_SEARCH_RESULTS = 5;

module.exports = {
    DEFAULT_PAGE_SIZE,
    DEFAULT_PAGE_NUMBER,
    GET_PRODUCTS_FIELDS,
    CACHE_DURATION,
    MAX_SEARCH_RESULTS
}